<?php

/**
 * Application Core Configuration
 * 
 * ------------------------------------------------------------------------
 * 
 * This configuration array defines the fundamental parameters and paths
 * that control the application's behavior and structure. It establishes
 * the site identity, directory structures, URI handling, and operational
 * mode.
 * 
 * ROOT_DIR and BASE_URI are defined by global cofigs/app.php and we are relying on that.
 * 
 */

return [
    /**
     * Website name/title used for browser tabs, SEO, and potentially
     * displayed in the header or other UI elements.
     */
    'title' => 'website_name',

    /**
     * Base URI for the application defining the root URL path.
     * This constant is typically defined in a bootstrap file and
     * forms the foundation for all application URLs.
     */
    'base_uri' => BASE_URI,

    /**
     * Optional prefix appended to all URIs generated by the application.
     * Empty string indicates no prefix will be used.
     * Useful for subdirectory deployments or API versioning.
     */
    'uri_prefix' => '',

    /**
     * Absolute filesystem path to the application's root directory.
     * This constant is typically defined in a bootstrap file and
     * serves as the reference point for all directory paths.
     */
    'root_dir' => ROOT_DIR,

    /**
     * Directory where additional configuration files are stored.
     * These may include database settings, third-party integrations,
     * feature flags, localization settings, etc.
     */
    'config_dir' => ROOT_DIR . '/web/configs/',

    /**
     * Directory containing route definitions that map URLs to controllers.
     * These files define the application's URL structure and determine
     * which code handles specific requests.
     */
    'routes_dir' => ROOT_DIR . '/web/routes/',

    /**
     * Directory where user-uploaded files are stored.
     * This path should typically be writable by the web server
     * but protected from direct execution of uploaded content.
     */
    'uploads_dir' => ROOT_DIR . '/static/uploads/',

    /**
     * Application operating mode flag.
     * - When true: Enables verbose error reporting, logging, and debugging tools
     * - When false: Production mode with minimal error exposure to end users
     * Should be set to false in production environments for security.
     */
    'isDebug' => true
];
